export const enum AppErrorCode {
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  SERVER_ERROR = "SERVER_ERROR",
  
}
